### ISSUE TITLE
Semester 2, Assignment 1 

### ISSUE THREAD

**Issue by IllustratedMan-code** [IllustratedMan-code/SeniorProject#16]
# Part I. Description of Overall Test Plan
Provide one to three paragraphs describing general testing strategies employed by your project.

# Part II. Test Case Descriptions
List a series of 10-25 tests for validating your project outcomes. For each test case provide the following:
1.  test case identifier (a number or unique name)
2.  purpose of test
3.  description of test
4.  inputs used for test
5.  expected outputs/results
6.  normal/abnormal/boundary case indication
7.  blackbox/whitebox test indication
8.  functional/performance test indication
9.  unit/integration test indication

Note that some of these categories may be inappropriate for your project and may be omitted if you can justify doing so. For items 6-9, only one term should apply.

# Part III. Test Case Matrix: summarizes the test case coverage (items 1, 6-9 in a tabular format)

**Comment by IllustratedMan-code** [comment]
Since we currently have no automated testing (other than John's auto builds), we should cover this on our meeting (1/9/2024).

There is this testing framework: https://github.com/bitwes/Gut

C++ has built in testing, see: https://docs.godotengine.org/en/stable/contributing/development/core_and_modules/unit_testing.html

Testing in game development is a bit tricky anyway, but we can certainly set up tests for the various functions we use. We should come up with a way to automatically test scenes, but I'm not entirely sure how. We could also come up with a manual checklist that needs to be done everytime something is merged into main.

**Comment by IllustratedMan-code** [comment]
# Part 1
There are two main phases employed for testing. First, automated testing is used to ensure function output is what is desired. Second, methodical manual testing is employed to ensure that each "scene" in the project is functioning as expected. 

In terms of automated testing, the project is using the Godot addon [Gut](https://github.com/bitwes/Gut) to manage unit and integration tests. We had to manually install Gut into our project using the latest main branch rather than through the addon store as it conflicted with our strict type annotation setup. Gut allows us to write unit and integration tests similar to those of the python unit testing framework. Our goal is to have high testing coverage for functions created within Gdscript.

For the manual testing phase, each playable scene will be tested individually until "completion", i.e. playing a minigame through all possible states (winning, losing) and identifying any errors found. Once all scenes are tested individually, an examination of the connection between scenes will take place. This means menu functionality, pause menu, etc. After the manual phase is complete, the game is ready to be tested by outsiders not directly involved in the project.

**Comment by IllustratedMan-code** [comment]
Here is how I am setting up the naming schema for my tests:
test_*ScriptName*_*FunctionName*

I need a csv for part 3, so just edit my csv comment

**Comment by IllustratedMan-code** [comment]
# CSV (part 3)

```
name,normal/abnormal/boundary,whitebox/blackbox,unit/integration
test_DNA_reciprocal_sequence,normal,black,functional,unit
test_DNA_sequence,normal,blackbox,functional,unit
test_DNA_string_to_sequence,normal,blackbox,functional,unit
test_Globals_NitrogenousBaseDetails,normal,blackbox,functional,unit
test_DNA_sequence_nodes,normal,whitebox,functional,unit
```

**Comment by IllustratedMan-code** [comment]
# Part 2
### test_DNA_reciprocal_sequence
1. Purpose: Ensure that the reciprocal_sequence function returns an array of enum values corresponding to the reciprocal DNA sequence of the DNA scene
2. Description: Creates a DNA node with a specific sequence, runs "reciprocal_sequence", and asserts output to manually given reciprocal sequence
3. Inputs: Initial sequence of nucleotides given as a string
4. Outputs: reciprocal sequence given as a list of enum values of the NitrogenousBase type
5. normal
6. blackbox
7. functional
8. unit
### test_DNA_sequence
### test_DNA_string_to_sequence
### test_Globals_NitrogenousBaseDetails
### test_DNA_sequence_nodes

**Comment by adediu25** [comment]
# Part 3

**Comment by adediu25** [comment]
PDF Version:
[Assignment1_SeniorDesign.pdf](https://github.com/quaternary-game/class-work/files/14004302/Assignment1_SeniorDesign.pdf)
