### ISSUE TITLE
Topics

### ISSUE THREAD

**Issue by IllustratedMan-code** [IllustratedMan-code/SeniorProject#2]
I've got a few ideas:
1. videogame/education tool (genetics related?)
2. rewrite/redesign/reverse-engineer a program from a non-programmer space (this is a good candidate: https://bioconductor.org/packages/release/bioc/html/DiffBind.html). I think this is the easiest one?
3. write a language (probably lisp) in rust with stretch goals like a just in time compiler, LLVM backend, etc.
4. Some graphical analysis tool for large datasets
5. John had an idea about an alternative to tile which was cool, but it sounded impossible for our budget ($0)

Would love some suggestions and or votes for ideas.

**Comment by john-whiting** [comment]
I don't have more to add, but #1, #3, or #4 has my vote.

**Comment by IllustratedMan-code** [comment]
We're going with 1!
