### ISSUE TITLE
Team Contract

### ISSUE THREAD

**Issue by IllustratedMan-code** [IllustratedMan-code/SeniorProject#4]

**Comment by IllustratedMan-code** [comment]
# Project Focus: Genetics video game

Teach kids genetics/biology concepts in a fun way through a game. This might
include concepts like natural selection and mendelian genetics (punnet squares).


# Team Members

-   David Lewis (lewis3d7@mail.uc.edu)
-   John Whiting (whitinjp@mail.uc.edu)
-   Alex Dediu (dediuai@mail.uc.edu)
-   Connor McKinney (mckinncr@mail.uc.edu)


# Team Responsibilities

-   Attend 1-2 in-person/virtual meetings per week, depending on need (Mondays
    7:00 PM)
-   Reply to discord messages/emails in a timely fashion (24 hours)
-   Respect team members (attend meetings on time)
-   Reach out for help if needed, don&rsquo;t wait for meetings
-   Carry your weight (try your best to contribute equally to the project)


# Specific Responsibilities


## Alex

-   Programmer
-   Tester


## Connor

-   Programmer
-   Tester


## David

-   Educational Content Lead
    -   Decides what content should be covered
-   Programmer


## John

-   Software Stack Lead
    -   Manages code style/tech stack
-   Programmer

**Comment by IllustratedMan-code** [comment]
Approved by David Lewis

**Comment by john-whiting** [comment]
Looks good to me!

**Comment by ConnorMcKinney99** [comment]
Approved by Connor McKinney

**Comment by hawkinsw** [comment]
Good work! I am sure that you all agreed on this but it just doesn't seem explicit: Are you planning on the Monday meetings being online or in person? Again, I am sure that you already hammered this out, but I thought I would ask anyway.

Otherwise, LGTM!

**Comment by IllustratedMan-code** [comment]
We're going with virtual unless there is some reason we really need to meet in person. Thanks for the feedback!

**Comment by hawkinsw** [comment]
> We're going with virtual unless there is some reason we really need to meet in person. Thanks for the feedback!

Great!

**Comment by adediu25** [comment]
Approved by Alex Dediu
